# Site settings
title: "Shakti Prasad Padhy, Ph.D."
email: "padhy.shaktiprasad@gmail.com"
description: >-
  Leveraging AI-driven frameworks and high-throughput experiments to 
  revolutionize materials discovery and design for renewable energy, 
  aerospace, and biomedical applications. 
url: "https://www.shaktippadhy.com"
baseurl: ""
lang: "en"
timezone: "Asia/Singapore"

# Theme & Skin
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "custom"  

# SEO
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Markdown
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Search
search: true

# Navigation (header)
navbar:
  logo:
    icon: "fab fa-github"
    url: "/"
  links:
    - title: "About"
      url: "/about/"
      header: true
    - title: "Projects"
      url: "/projects/"
      header: true
    - title: "Blog"
      url: "/blog/"
      header: true
    - title: "Contact"
      url: "/contact/"
      header: true

# Author info
author:
  name:   "Shakti Prasad Padhy, Ph.D."
  avatar: "/assets/images/bio-photo.jpg"
  bio: |
    Incoming Postdoctoral Researcher, Texas A&M University, USA
    Ph.D. Materials Science & Engineering, NTU, Singapore
    Materials Informatics Researcher
    Automated & High-Throughput Experimentation
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:padhy.shaktiprasad@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/shakti-prasad-padhy"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Shakti-95"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=1yxyKvEAAAAJ"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Shakti-Padhy"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/shakti-prasad-padhy"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Shakti-95"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=1yxyKvEAAAAJ"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Shakti-Padhy"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# Include additional directories
include:
  - _pages
